# ── Local overrides ───────────────────────────────────────────
spring.datasource.url=jdbc:mysql://localhost:3309/urlshortener?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

spring.data.redis.host=localhost
spring.data.redis.port=6382

server.port=8083

app.base-url=http://localhost:8083

logging.level.com.shank.urlshortener.controller=INFO
logging.level.com.shank.urlshortener.service=INFO
