version: '3.8'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: urlshortener
    ports:
      - "3309:3306"
    volumes:
      - urlshortener_mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6382:6379"
    container_name: urlshortener-redis
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru

volumes:
  urlshortener_mysql:
